### ISSUE TITLE
Merging and review of PR's is taking too long

### ISSUE THREAD

**Issue by brayo-pip** [TheAlgorithms/Go#130]
I feel that the rate at which PRs are merged will have a huge impact on the growrate of this repo's codebase. Right now we are still implementing the basic algorithms, and it really should not take this long to review our commits. You could also grant write access to the more active developers,xd.

**Comment by mateuszz0000** [comment]
@cclauss I am willing to help but for the few first review I will need you to help.

**Comment by brayo-pip** [comment]
am officially a member of the org am going to merge or close most these PRs now
