### ISSUE TITLE
Need more test files 

### ISSUE THREAD

**Issue by rajneesh44** [TheAlgorithms/Go#145]
Need to write test.go files for the following ```unmarked``` directories as we are using non-executable packages. (no ```package main``` at the top)
* [ ] ciphers
* [ ] data-structures
* [ ] dynamic-programming
* [ ] other
* [x] searches
* [x] sorts
* [ ] strings

**Comment by tjgurwara99** [comment]
Closing this to keep track of this issue under a unified issue #272
