### ISSUE TITLE
Naming issues in the strings directory

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Go#149]
@halafi Can you please make some changes in https://github.com/TheAlgorithms/Go/tree/master/strings ?

1. The directories contain spaces instead of dashes in the directory names.  This forces us to [quote the directory names](https://github.com/TheAlgorithms/Go/blob/master/.github/workflows/golangci-lint.yml#L33) when using command line tools such as linters.
2. File names need work also.  Is `ac.go` a calculation for alternating current or is it controller for an air conditioner?  Is `bom.go` a tool for building a bill of materials or does it generate a byte order mark?  Why does the reader have to guess??  `aho-corasick.go` is a much more self-documenting filename than `ac.go`.
3. Can you help us to get the last two lines of `.github/workflows/golangci-lint.yml` to pass without `|| true`?

**Comment by piyushs2894** [comment]
@cclauss I have fixed the issues 1 and 2 and looking for 3rd as well. Can u please review and merge below PR for the same with "hacktoberfest-accepted" label.
https://github.com/TheAlgorithms/Go/pull/209

**Comment by piyushs2894** [comment]
@cclauss Regarding golandci-lint failure, it is failing as in single_string_matching and multiple_string_matching directory, some methods like main, commandLineInput, and many more more are redeclared. Go does not allow same method name in single package. Is it has to be fixed ?
