### ISSUE TITLE
Code style and tests

### ISSUE THREAD

**Issue by L3str4nge** [TheAlgorithms/Go#152]
Hello, have you consider any code style like in https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#coding-style ? I don't see any `CONTIRBUTING.md` file in this repo. Maybe it will be worth it? How about using `gofmt`:https://golang.org/doc/effective_go.html#formatting ?

My second question is: can we add unit tests to github action? For now we only have lint check.

**Comment by brayo-pip** [comment]
Hey I 'go fmt-ed' most of the Repo maybe u can write the contributing.md?

**Comment by cclauss** [comment]
`go fmt` is the standard for Go and fortunately, there is no other!

Are you folks OK with the GitHub Actions https://github.com/TheAlgorithms/Go/tree/master/.github/workflows ?

**Comment by brayo-pip** [comment]
Am not good with GitHub actions, anyway could u find a way to automate 'go fmt' once new code is merged. I automating it with subprocess.run() in python but for some reason it doesn't work on linux. Maybe u will be luckier

**Comment by brayo-pip** [comment]
Do we need custom packages such as 'sorts' package or would we rather have the main function for each file? I think most ppl don't have the time or expertise to import these custom packages and run them. Choosing to simply use the main package maybe the way to go... what do u guys think?
