### ISSUE TITLE
Proposal: Testing revamp

### ISSUE THREAD

**Issue by willdavsmith** [TheAlgorithms/Go#198]
I was looking over this repository and I noticed that lots of the files have commented out testing methods, however some have no proper tests. It seems to me that there's no centralized testing for the repository, and I think that it would be beneficial. 

Proposal:
* Centralized testing (go test) for entire project at once
* Integration with CI (Github actions - test and lint on each new PR)
* Code cleanup and migration of tests in main() methods to unit tests

Thoughts? I would be happy to work on this if others think it would be useful!

In the file [golangci-lint.yml](../blob/master/.github/workflows/golangci-lint.yml)...
* [x] Remove `|| true` from ciphers -- Fixed in #222
* [x] Remove `|| true` from data-structures/binary-tree
* [x] Remove `|| true` from data-structures/dynamic-array
* [x] Remove `|| true` from data-structures/hash-map -- Fixed in #222
* [x] Remove `|| true` from data-structures/linked-list
* [x] Remove `|| true` from data-structures/trie
* [x] Remove `|| true` from dynamic-programming
* [x] Remove `|| true` from other
* [x] Remove `|| true` from searches
* [x] Remove `|| true` from "strings/multiple string matching"
* [x] Remove `|| true` from math/sieve

**Comment by vedantmamgain** [comment]
Alongside Centralized testing, I believe a README containing benchmark of all the sorts and searches must be added as well.

**Comment by enrinal** [comment]
I think it's good idea for centralized testing.

**Comment by cclauss** [comment]
Nice initiative -- I am highly supportive.  Let's get the continuous integration tests passing again.  Merging PRs when tests are failing is just dangerous.  @Mystigan, can you please help to make this happen?

**Comment by Mystigan** [comment]
@cclauss , I agree with the points made.
- We can begin our cleanup with the files that are failing the CI test(from the strings folder AFAIK) and proceed from there.
- About centralized testing and adding it as part of CI, I would need some help with this as I haven't done this before.
- Also, to ensure it doesn't  turn ugly again, we should setup a set of guidelines for contributors so that they have an idea about the structure expected (for code as well as issues and PRs). To this end, so far, I have added some basic templates for issues and PRs. Please go through them and suggest changes, if any.

**Comment by Mystigan** [comment]
So I have fixed the issues in the two files in strings folder which were causing the ci lint to fail. But for existing PRs, how do we update them? Will running `git pull upstream master` and then a `git push origin master` work? Or is there any other way to get this done?

**Comment by vedantmamgain** [comment]
@Mystigan  The math folder isn't included in the ci YAML file. Can you fix that?

**Comment by Mystigan** [comment]
> @Mystigan The math folder isn't included in the lint YAML file. Can you fix that?

As mentioned in #221 , entries for each sub folder in "math" has been added in CI lint yaml file. Once the issue with sieve.go is fixed, we can replace these entries with a single recursive entry for "math".

**Comment by cclauss** [comment]
In looking through our open issues, I see that most of them are [`automated testing` related](https://github.com/TheAlgorithms/Go/issues?q=is%3Aissue+is%3Aopen+label%3A%22automated+testing%22).  Please read thru the issues with this label and try to unify them under this ___tracking issue___.  Please maintain an up-to-date task list at the top of this issue so we can all see the work plan and status at a glance.  This allows contributors with a few minutes to spare to work to tick off one of the tasks.  Divide and conquer...

**Comment by cclauss** [comment]
How are we doing on this issue?

**Comment by tjgurwara99** [comment]
closed in #266
