### ISSUE TITLE
Implement Fibonacci sequence in dynamic programming

### ISSUE THREAD

**Issue by Gituser143** [TheAlgorithms/Go#228]
**Description**
Currently the dynamic programming examples, no implementation of Fibonacci sequence has been made. This is by far the most common and beginner friendly example for dynamic programming. I would like to implement the same.

For new implementation:
- Fibonacci sequence using dynamic programming.

**Comment by abrahamfrancis** [comment]
Can I take this up?

**Comment by IanvsPoplicola** [comment]
I've opened a PR with a pretty basic implementation of this 🙂
