### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Go#257]
**Description**
The currently README file is not appropriate. Instead of describing a few algorithms, it should contain
- general information about the repo
- link to guidelines 
- directory structure

Take reference from the following README files
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/README.md
https://github.com/TheAlgorithms/Python/blob/master/README.md

**Comment by vedantmamgain** [comment]
Sure
