### ISSUE TITLE
Fix the failing rsa tests

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Go#268]
**Describe the bug**
Fix the failing `rsa` tests so they pass and then remove `| grep -v /rsa` from
* https://github.com/TheAlgorithms/Go/blob/master/.github/workflows/golangtests.yml#L13

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tjgurwara99** [comment]
I'm rewriting this from scratch and have added a PR #288 to make it easier to separate concern of algorithms.
