### ISSUE TITLE
Feat: Consider adding proper documentation for algorithms

### ISSUE THREAD

**Issue by tjgurwara99** [TheAlgorithms/Go#277]
**Description**
Currently the repository is in a good condition to start thinking about how to better explain things to students. I personally use TheAlgorithms repositories for inspiration, so I think it should be great if we can start writing good documentation which can make it easier for us students to understand the nitty-gritty of algorithms better.

For new implementation:
- Documentation: The GoDoc org provides a very clean and elegant way of showing documentation of your repositories. For example, if you just go to the link `https://pkg.go.dev/github.com/TheAlgorithms/Go/` [here](https://pkg.go.dev/github.com/TheAlgorithms/Go/), you will see that this repository's documentation works but it isn't up to good standards (for lack of a better word).

For enhancement:
- Specify what needs to be changed and why. For example:
  - To improve the documentation, I propose we start writing documentation in a way that works well with the GoDoc orgs system. Whilst this may take some time, I believe this is achievable and would help raise the standards for this repository. In the meantime, we should ask the PR authors to check whether their code's documentation is up to standards by asking them to check their fork's documentation using `https://pkg.go.dev/github.com/<username>/Go/` and accept them if this is well written.

Do let me know of your thoughts. I'm also open to suggestions for creating a automated documentation using GitHub-pages. In my personal opinion, the styling for the godoc command is very simple and therefore I personally prefer the GoDoc org's documentation generation. (To be fair, we cal also automate the styles from GoDoc org's pages with the wget command but it may take some time to get it right.)

**Comment by tjgurwara99** [comment]
Any updates?

**Comment by mohamed-abdelrhman** [comment]
+1 here for the GoDoc

**Comment by tjgurwara99** [comment]
current up to date (as of 7 Sep 2021) documentation [TheAlgorithms/Go docs](https://pkg.go.dev/github.com/TheAlgorithms/Go)
