### ISSUE TITLE
Quicksort doesn't sort in-place

### ISSUE THREAD

**Issue by brayo-pip** [TheAlgorithms/Go#303]
Quicksort doesn't sort in place. I was studying algorithms the other day and decided to try and implement quicksort in go. It was apparent that implementing an in place sorting algorithm would be tedious involving pointers and pointer indirection, so I decided to check the one already implemented here. And it's implementation is incorrect. It's still close enough to quicksort but the additional work that goes on to combine slices adds an overhead that shouldn't be there with quicksort. I will make a PR to address this soon!

**Comment by siriak** [comment]
Hi, could you add a PR number here? I'll gladly review it. I totally agree with you that this bug should be addressed.

**Comment by tjgurwara99** [comment]
I think the author has solved this in this a26459b.
