### ISSUE TITLE
Big changes coming!

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/Go#317]
Hi everyone, as you may have noticed, there's some activity going on recently in this repo. That's me cleaning it up :) I'm a new maintainer of this repo and will do my best to review and give feedback on new PRs. There are a lot of old ones at the moment and I'm not a Go expert to try and fix issues found in them on my own. So, please update your PRs by merging in the latest master branch and making sure that all checks pass. I'll try to review as many PRs as I can as soon as possible, but many of them will be closed by stale bot too. If your PR is marked as stale, please comment on it to show that it's not abandoned and I'll review it when time allows.

**Comment by Miraddo** [comment]
Hi Andrii, I'm glad to see you here,
And thanks for accepting my last pull request.
I'll help to make our Go repository more clear based on guidelines,
I'm not an expert as well, but I try my best to create test cases and add new algorithms to the repository.
