### ISSUE TITLE
Directory tree is not reflected properly in readme

### ISSUE THREAD

**Issue by oskarwojciski** [TheAlgorithms/Go#344]
**Describe the bug**
The readme contains links to files in different directories than actual ones. For example, directory is `cipher` and readme is linking to `ciphers`

**Comment by siriak** [comment]
Thanks for bringing this up, could you make a pr to fix that?

**Comment by tjgurwara99** [comment]
Thanks for raising this and opening the PR. I'm currently working on a tool to automate this but it will take some time as I only get time in the weekends 😅.

**Comment by oskarwojciski** [comment]
So far the issue is fixed. I think that automated tool will be much more reliable, but for now, I am closing the issue :)
