### ISSUE TITLE
the "Code Formatter" section of CONTRIBUTING.md just contains go installation instructions

### ISSUE THREAD

**Issue by lostbearlabs** [TheAlgorithms/Go#359]
**Describe the bug**

In the file CONTRIBUTING.md, there is a section with the heading  "Code Formatter".  This section describes how to install go, and it has build instructions that may be out of date since they refer to the nonexistent file "main.go"

**To Reproduce**
1. View the file https://github.com/TheAlgorithms/Go/blob/master/CONTRIBUTING.md

**Expected behavior**

- I would expect this section to contain instructions something like "run the command go fmt".
- I would expect the existing content to be in an earlier section of the document with a header like "Installing Go"
- It might be helpful for beginners if there was a unified section of the document with sub-sections for installing go, running the existing code, formatting code, etc.  The section on preparing pull requests could then just reference the earlier section.

**Comment by tjgurwara99** [comment]
Agreed, it should be updated. Feel free to open a PR for it. Me and other maintainers would be happy to take a look.

**Comment by nikzayn** [comment]
I would like to take this one issue
