### ISSUE TITLE
Improve package organizations

### ISSUE THREAD

**Issue by eduardogr** [TheAlgorithms/Go#36]
There's a lot of main packages in this project

> sorts/selection_sort.go:1:package main
sorts/Heapsort.go:1:package main
....
....
other/PasswordGenerator.go:5:package main
other/PrimeNumbers.go:1:package main
>
We can improve this package organization to let each package have its place

**Comment by localleon** [comment]
+1 

This would also fix all the failed golangci-lint test. Currently they fail because multiple people use the package main.

**Comment by nomisrevol** [comment]
It's a good idea. I'm trying to fix this (both package and filename convention). I'm starting with sorts. You're welcome to help with other parts.

**Comment by eduardogr** [comment]
How is this going? Do you need help with this?

**Comment by vedantmamgain** [comment]
@eduardogr  That would be great if you can improve the package organization.

**Comment by tjgurwara99** [comment]
I believe this issue has been resolved with the PR #266
