### ISSUE TITLE
Add more Algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Go#4]
Please add more algorithms to this repo. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by DanGarcia595** [comment]
I have some implementations that I made in my CIS class last year that I can add.

**Comment by dynamitechetan** [comment]
sure

**Comment by brainsnail** [comment]
Anything in particular you'd like to see added?

**Comment by jrolheiser-va** [comment]
I'd like to contribute, but also think this project could use some restructuring to make it more similar to the other ones in https://github.com/TheAlgorithms. Like breaking out files into common groups like `sorting`, `searching`, `network flow`, etc..

I am also a big fan of unittests for stuff like this. Not sure what others think.

**Comment by dynamitechetan** [comment]
@brainsnail Feel free to add whatever you like.

**Comment by EyesBear** [comment]
Interested.

**Comment by himanshub16** [comment]
Hey,
I would like to add the following topics:
* LinkedList
* Stack
* Queue
* Binary Tree

Will add more to the list if possible. :smiley:

**Comment by niranjan92** [comment]
I can add topological sort :)

**Comment by shady831213** [comment]
Add some data structure:).
add fibonacci heap, reduced-space-vanEmdeBoas-tree and disjoint-set-tree #31

**Comment by LockGit** [comment]
have some easy go [implementation](https://github.com/LockGit/Go)
https://github.com/LockGit/Go

**Comment by anand371** [comment]
would adding kadanes largest sum contiguous sub array algorithm be a good idea?
