### ISSUE TITLE
Does the LGTM tool ever find any issues that are useful to fix???

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Go#422]
For Python, the LGTM tool is nearly useless so we got rid of it.  Is the same true for Go?

**Comment by tjgurwara99** [comment]
Should we get rid of it? I don't think LGTM is useful at all for us - in fact, it slows down the workflows passing.

**Comment by raklaptudirm** [comment]
I think we should get rid of it.

**Comment by tjgurwara99** [comment]
@siriak Do you have permission to remove the LGTM analysis from this repo? If so, could you remove it?

**Comment by siriak** [comment]
I don't have, this this needs to be done via their website

**Comment by cclauss** [comment]
@poyea ?

**Comment by poyea** [comment]
@cclauss I think it depends on what else does the Go repository have. If there are enough checks, I think it makes perfect sense to deprecate it. I assume @dynamitechetan or the owners should have rights to disable it?

**Comment by cclauss** [comment]
> If there are enough checks

https://github.com/TheAlgorithms/Go/tree/master/.github/workflows seems to provide appropriate (and fast) test coverage.

**Comment by poyea** [comment]
> > If there are enough checks
> 
> https://github.com/TheAlgorithms/Go/tree/master/.github/workflows seems to provide appropriate and fast test coverage.

I believe so. I think any maintainers can disable it on their website then. cc @AnupKumarPanwar

**Comment by tjgurwara99** [comment]
<img width="1677" alt="Screenshot 2022-03-29 at 13 17 52" src="https://user-images.githubusercontent.com/21105489/160609453-7af7c1a9-09a0-4442-80fe-43ca3b7f4c2c.png">

Maintainers can't do that unfortunately - only admins can. cc @siriak
