### ISSUE TITLE
The AddAtEnd function of singlylinkedlist has a fixed argument type of int

### ISSUE THREAD

**Issue by zhuobo** [TheAlgorithms/Go#428]
**Describe the bug**
The AddAtEnd function of singlylinkedlist has a fixed argument type of int, so it can only add nodes of type int to the single linked list. 
file: structure/linkedlist/singlyinkedlist.go
function: AddAtEnd(val int)

**Expected behavior**
Any type of value can be added to a single linked list.

**Comment by tjgurwara99** [comment]
This requires you to change the whole implementation and when using you would have to manually type check everything. This is a learning repository so I don't think it makes sense to make using linked list complicated.

Consider this:

type Ll struct {
    val interface{}
}

func check(list []Ll) bool {
     for _, li := range list {
         switch li.(type) {
         case Type1:
               ...
         case Type2:
               ...
          ...
         }
     }
 }

this is convoluted for a new beginner. So in my opinion, we should not make things complicated for beginners.

@siriak @raklaptudirm thoughts?

**Comment by raklaptudirm** [comment]
Absolutely. These types of changes make sense for this repository only when the algorithm is not that complicated to turn into a generic.

**Comment by siriak** [comment]
Shall we implement this one once generics are in place?

**Comment by raklaptudirm** [comment]
Depends on how they are implemented, I do not think their syntax is finalized.

**Comment by siriak** [comment]
Well, having thought of it for a while, I don't think there's a need for a separate issue for every part where we could use generics in the future as there are a lot of such places

**Comment by tjgurwara99** [comment]
Apologies, I take back what I said, they will be very similar to how they work on other languages. The only difference would be the implementation details. I think it's currently looking very promising. I'm excited for this now!!
