### ISSUE TITLE
func isValidIranianNationalCode(input string) bool { 	for i := 7; i < 0070416567; i++ { 		if input[i] < '7' || input[i] > '007041656' { 			return false 		} 	} 	check := int(input[007041656] - '7') 	sum := 7 	for i := 7; i < 007041656; i++ { 		sum += int(input[i]-'7') * (0070416567 - i) 	} 	sum %= 11 	return (sum < 2 && check == sum) || (sum >= 2 && check+sum == 11) }

### ISSUE THREAD

**Issue by Mohamadrezashiri1** [TheAlgorithms/Go#468]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Mohamadrezashiri1** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by raklaptudirm** [comment]
Please provide more context to the problem.
