### ISSUE TITLE
Bump Go to 1.18 for generics implementation

### ISSUE THREAD

**Issue by paul-leydier** [TheAlgorithms/Go#478]
Hi everyone!

I was wondering, what is your position regarding the implementation of algorithms using generics on this repo?

Are you waiting a bit longer before upgrading to [go 1.18](https://tip.golang.org/doc/go1.18), or should we do it now so that we can already start getting hands-on experience with generics?

If so, I recommend using the constraints defined in [golang.org/x/exp/constraints](https://pkg.go.dev/golang.org/x/exp/constraints) as standard constraints!

**Comment by tjgurwara99** [comment]
I'm more than happy to bump the version now and I was thinking to start it but we need to do a bit of cleanup of the repository structure. Currently its all over the place 😓

I'll be opening a series of PR's to make these changes in an incremental (and traceable) way – will keep posting updates on this issue.

**Comment by tjgurwara99** [comment]
closed in #483
