### ISSUE TITLE
Feat: Consider adding code scanning alerts

### ISSUE THREAD

**Issue by tjgurwara99** [TheAlgorithms/Go#490]
**Description**
Now that we have removed LGTM from this repo, I think its worth considering adding CodeScanning to this repository. It's quite similar to LGTM in a lot of ways but there are subtle differences that may be quite useful but at the same time it might be redundant so thought I should open it here and trial it out. What do you guys think?

For enhancement:
- Enable CodeScanning in this repo - on a trial basis to see if its useful.
  - If it turns out that its not useful (similar to LGTM) then we will remove it.

**Comment by siriak** [comment]
Can we close this one?

**Comment by raklaptudirm** [comment]
We still do not have any updates on wether the scanning is really necessary, so leave it open.

**Comment by raklaptudirm** [comment]
@tjgurwara99 @siriak What are your opinions, is the code scanning necessary?

**Comment by tjgurwara99** [comment]
I think it's not useful for Go, we can remove it from the repo.
