### ISSUE TITLE
Traversal is error of binary-tree.go.

### ISSUE THREAD

**Issue by keob** [TheAlgorithms/Go#50]
Traversal is error of binary-tree.go.
```golang
// LNR
func inorder(n *node) {
	if n == nil {
		return
	}
	inorder(n.left)
	fmt.Print(n.val, " ")
	inorder(n.right)
}

// NLR
func preorder(n *node) {
	if n == nil {
		return
	}
	fmt.Print(n.val, " ")
	preorder(n.left)
	preorder(n.right)
}

// LRN
func postorder(n *node) {
	if n == nil {
		return
	}
	postorder(n.left)
	postorder(n.right)
	fmt.Print(n.val, " ")
}
```

**Comment by Abuubkar** [comment]
What error do you encounter? and does it still not fixed if not tell me i will fix it

**Comment by keob** [comment]
I am sorry to turn off the issues.Before i new issues in #97 to fix it.
________________________________
发件人: Abubakar Khawaja <notifications@github.com>
发送时间: 2019年11月29日 22:13
收件人: TheAlgorithms/Go <Go@noreply.github.com>
抄送: babybug <bugbinbo@outlook.com>; Author <author@noreply.github.com>
主题: Re: [TheAlgorithms/Go] Traversal is error of binary-tree.go. (#50)


What error do you encounter? and does it still not fixed if not tell me i will fix it

―
