### ISSUE TITLE
LFU cache implementation

### ISSUE THREAD

**Issue by itsAkshayDubey** [TheAlgorithms/Go#531]
Hi,

I have not seen any implementation of [least frequently used cache](https://en.m.wikipedia.org/wiki/Least_frequently_used) in this repo.
Could you please assign this issue to me?

Regards,
Akshay

**Comment by sandyydk** [comment]
@raklaptudirm Can I pick this up?

**Comment by raklaptudirm** [comment]
@sandyydk Sure.

**Comment by raklaptudirm** [comment]
Just open a pr and we will review it
