### ISSUE TITLE
Mergesort using goroutines 

### ISSUE THREAD

**Issue by CorentinGS** [TheAlgorithms/Go#552]
**Description**
It would be interesting to add a mergesort algorithm that uses goroutines. It's a good way to show how routines can be used to improve classical algorithm. 

For enhancement:
- Add a ParallelMergesort function that use goroutines  
- Benchmark & test it and compare how it performs against classical mergesort 

I can do a pr in the weekend if you are ok with that suggestion.

**Comment by raklaptudirm** [comment]
Don't open issues for missing implementations. Just create a pull request and we will review it.
