### ISSUE TITLE
Binary Indexed Tree (BIT) / Fenwick Tree Data structure

### ISSUE THREAD

**Issue by irfansofyana** [TheAlgorithms/Go#563]
**Description**

Binary Indexed Tree (BIT) or sometimes people called fenwick tree is a data structure that can be used to efficiently update elements and calculate [prefix sums](https://en.wikipedia.org/wiki/Prefix_sum) in a table of numbers.

Details: https://en.wikipedia.org/wiki/Fenwick_tree

For new implementation:
- Problem statement:
> We have an array arr[0 . . . n-1] and we have Q queries. In every query we can:
1 Compute the sum of the first i elements. 
2 Modify the value of a specified element of the array arr[i] = x where 0 <= i <= n-1.

It can be solved efficiently with Binary indexed tree

**Comment by irfansofyana** [comment]
I will be happy to work on this issue if it's okay

**Comment by raklaptudirm** [comment]
No need to open issues for missing implementations. Just open a pr and we will review it.
