### ISSUE TITLE
[OTHER] Add a GitHub Actions workflow to generate `DIRECTORY.md`

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Go#592]
### What would you like to share?

To make the algorithm addition process easier, we can make a GitHub Actions workflow to generate a `DIRECTORY.md` file.
Many repositories in the organization do this to keep things organized. We can use the workflow from the [**C++ repository**](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/.github/workflows/awesome_workflow.yml#L49).

What do you think? Thanks. 🙂

### Additional information

I'd like to work on this. 🙂

**Comment by raklaptudirm** [comment]
We already maintain a list of algorithms in our <samp>README.md</samp>.
