### ISSUE TITLE
Spelling mistake in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JahnabDutta** [TheAlgorithms/Go#629]
### Description

There is a spelling mistake in the third point `code` subheading of the `Making Changes` heading.
It reads- Use meaning variable names.
It should read -Use meaningful variable names.

### Steps to reproduce

1. Go to CONTRIBUTING.md
2. Go to **Making Changes** heading.
3. Go to **code** subheading.
4. The third point says **Use meaning variable names.**

### Excepted behavior

Change the third point to **Use meaningful variable names.**

### Screenshots

![image](https://user-images.githubusercontent.com/76475829/227725502-5f4ee938-7f39-4083-ab95-edf98f7bbe6c.png)

**Comment by siriak** [comment]
Thanks for reporting, could you fix that?
