### ISSUE TITLE
[ENHANCEMENT]: Strassen Matrix Multiplication Implementation in Go

### ISSUE THREAD

**Issue by mohit07raghav19** [TheAlgorithms/Go#661]
### What would you like to share?

**Strassen Matrix Multiplication** is an algorithm for multiplying two matrices that uses a **divide-and-conquer approach** to reduce the number of basic multiplications required, making it more efficient than the standard matrix multiplication algorithm, especially for large matrices. 

It reduces the time complexity to _O(n^log2(7))_ compared to naive approach _(O(n^3))_.

### Extra issue details

Refactoring the file and folders for better structure.
- Adding the code file in math/matrix folder

**Comment by raklaptudirm** [comment]
Don't open an issue for algorithm implementations. Just open the pull request and it will be reviewed.
