### ISSUE TITLE
[ENHANCEMENT] Replacing Parenthesis Algorithm

### ISSUE THREAD

**Issue by 11-aryan** [TheAlgorithms/Go#674]
### What would you like to share?

In #492, the algorithm for checking parenthesis seems to be redundant, as it merely checks if all the opened parenthesis are closed or not. Instead, a better algorithm would be to check if the parenthesis is valid or balanced, which is a very standard algorithm. 

### Extra issue details

For example, in the parenthesis sequence `)))(((`, the current algorithm would return `true` as initially, the `parcounter` is decremented due to `)` and then later incremented, eventually becoming 0, but this is invalid as the `)` has started before `(`.

**Comment by 11-aryan** [comment]
I have the optimized implementation for this. Can I create a PR if this issue is valid ?

**Comment by raklaptudirm** [comment]
Don't open issues for missing algorithms. Just open a pr and it will be reviewed.

**Comment by 11-aryan** [comment]
Should that be added as a new algorithm ?

**Comment by raklaptudirm** [comment]
Sure.

**Comment by 11-aryan** [comment]
What about the existing one ?

**Comment by raklaptudirm** [comment]
Since its an improvement, you can replace the existing algorithm.
