### ISSUE TITLE
Basic Caesar cipher implementation

### ISSUE THREAD

**Issue by RickDeb2004** [TheAlgorithms/Go#690]
### What would you like to share?

basic Caesar cipher implementation using for decryption and encryption of a text .
Example:
**Plain Text "HELLOWORLD"
Encrypted Text "CZGGJRJMGY"**

### Extra issue details

make sure implementing correct algorithm , you can use three functions like encrypt, decrypt and hashedLetter function.

**Comment by tjgurwara99** [comment]
It already exists [here](https://github.com/TheAlgorithms/Go/blob/master/cipher/caesar/caesar.go). Closing this now since this is unlikely to be accepted again.
