### ISSUE TITLE
[ENHANCEMENT] add approximation algorithms + some topics in geometry

### ISSUE THREAD

**Issue by jafar75** [TheAlgorithms/Go#707]
### What would you like to share?

Hi,
I have a question about limitations and policies to add new algorithms to repo. I've a background in algorithms (MSc) and wanted to add some new algorithms if possible:

1- approximation algorithms, e.g. Christofides algorithm used for approximation of travelling salesman problem, covering problems
2- geometrical algorithms, e.g. Point location, convex hull, triangulation, etc

Is my suggestions, have any probable conflicts with future roadmap of the repo?

tnx

### Extra issue details

Implement approximation and geometrical algorithms

**Comment by raklaptudirm** [comment]
There is no need to open issues regarding the implementation of algorithms. We will accept implementations as long as the algorithm is non-trivial (has _some_ educational value) and the implementation follows our [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/master/CONTRIBUTING.md). Open a pull request with your algorithm and it will be reviewed.

**Comment by jafar75** [comment]
Thanks 🙏
