### ISSUE TITLE
Rail fence cipher new impl

### ISSUE THREAD

**Issue by Chandrahas77** [TheAlgorithms/Go#713]
### What would you like to share?

Wan't to add implementation of rail fence cipher which is a classical type of transposition cipher.

### Extra issue details

In the rail fence cipher, the plaintext is written downwards diagonally on successive "rails" of an imaginary fence, then moving up when the bottom rail is reached, down again when the top rail is reached, and so on until the whole plaintext is written out. The ciphertext is then read off in rows.

### Additional information

Have implemented the above code with clean code and added tests to it. So if you approve this issue please provide me with the write access such that I can push code to feature branch and raise a pull request.

**Comment by raklaptudirm** [comment]
No need to open issues for algorithms, just implement and open a pull request and it will be reviewed.

**Comment by Chandrahas77** [comment]
Hi @raklaptudirm @yanglbme Could you please have a look at this attached PR https://github.com/TheAlgorithms/Go/pull/715 for this issue?
