### ISSUE TITLE
Add license to the repository.

### ISSUE THREAD

**Issue by walter-ind** [TheAlgorithms/Go#90]
Adding license to the repository officially allows the developers/coders to modify and enhance the code.
If you allow me, I will submit a PR which will add license to this repository and hence close this issue.

**Comment by walter-ind** [comment]
@yanglbme Have a look at it.

**Comment by yanglbme** [comment]
ok @walter-ind

**Comment by walter-ind** [comment]
@yanglbme See my pull request.
